name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: lts
    - name: Install Dependencies
      run: npm install

    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true