name: Frontend Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - run: echo " The ${{ github.repository }} repository has been cloned to the runner." 

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 21

    - name: Install Dependencies
      run: npm install

    - run: npm run build --if-present
    
    - run: npm run test
      env:
        CI: true